name = "AssemblyLine2PC"
uuid = "91d0f3e7-927b-4e0e-b917-39e43e5ff890"
version = "1.0.0-DEV"
authors = ["LauBMo <laurea987@gmail.com> and contributors"]

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
MinerNumbers = "ddfd20ea-d9b0-4111-9c3d-a46b4fca4877"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[sources]
MinerNumbers = {path = "/home/laury/.julia/dev/MinerNumbers"}

[compat]
UnPack = "1.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
